// ------------------------------------------------------------------------------
//  <auto-generated>
//    This code was auto-generated by 'com.unity.microsoft.gdk.tools:GdkPlatformSettingsGenerator', version 
////    Changes to this file may cause incorrect behavior and will be lost when
//    regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace GdkSample_SignIn
{
public static class GdkPlatformSettings
{
#if UNITY_GAMECORE_XBOXSERIES
    public static string gameConfigTitleId = "60FCC671";
    public static string gameConfigScid = "00000000-0000-0000-0000-000060fcc671";
    public static string gameConfigSandbox = "";
#elif UNITY_GAMECORE_XBOXONE
    public static string gameConfigTitleId = "60FCC671";
    public static string gameConfigScid = "00000000-0000-0000-0000-000060fcc671";
    public static string gameConfigSandbox = "";
#else
    public static string gameConfigTitleId = "60FCC671";
    public static string gameConfigScid = "00000000-0000-0000-0000-000060fcc671";
    public static string gameConfigSandbox = "";
#endif
}
}
